# Generated by Django 3.2.9 on 2021-11-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0003_auto_20211122_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usu_id', models.IntegerField(max_length=3)),
                ('usu_nombre', models.CharField(max_length=75)),
                ('usu_pass', models.CharField(max_length=200)),
                ('rol_id', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='table_test',
        ),
    ]
