# Generated by Django 3.2.9 on 2021-11-29 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0005_auto_20211125_1814'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
